name: Format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format

      - name: Check formatting
        run: |
          files=$(git ls-files '*.cpp' '*.hpp' '*.h' '*.cc')
          if [ -n "$files" ]; then
            clang-format --dry-run --Werror $files
          fi

          - name: Generate compile_commands.json
        run: |
          cmake -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Run Clang-Tidy with Reviewdog
        uses: tnesanek/action-clang-tidy@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          target_files: 'src/*.cpp src/*.hpp'
